version: "3"

services:
  fast-tracker:
    image: node:15
    container_name: fast-tracker
    environment:
      SKIP_PREFLIGHT_CHECK: "true"
    ports:
      - "0.0.0.0:3000:3000"
      - "0.0.0.0:6006:6006"
    working_dir: "/app"
    volumes:
      - ./:/app
