version: "3.3"

services:
  app:
    image: cowglow/fast-tracker:${IMAGE_TAG}
    build:
      context: "services/app"
    container_name: fast-tracker
    environment:
      SKIP_PREFLIGHT_CHECK: "true"
    ports:
      - "3000:3000"
      - "6006:6006"
    working_dir: "/app"
    volumes:
      - ./services/app:/app
